// mappings.js

const COUNTRY_MAP = {
  // --- North America ---
  'us': 'United States', 'usa': 'United States', 'u.s.a.': 'United States', 'united states': 'United States', 'united states of america': 'United States',
  'ca': 'Canada', 'can': 'Canada', 'canada': 'Canada',
  'mx': 'Mexico', 'mex': 'Mexico', 'mexico': 'Mexico',

  // --- Europe ---
  'gb': 'United Kingdom', 'uk': 'United Kingdom', 'u.k.': 'United Kingdom', 'great britain': 'United Kingdom', 'united kingdom': 'United Kingdom', 'england': 'United Kingdom', 'scotland': 'United Kingdom', 'wales': 'United Kingdom', 'northern ireland': 'United Kingdom',
  'ie': 'Ireland', 'ireland': 'Ireland',
  'de': 'Germany', 'ger': 'Germany', 'germany': 'Germany',
  'fr': 'France', 'fra': 'France', 'france': 'France',
  'it': 'Italy', 'ita': 'Italy', 'italy': 'Italy',
  'es': 'Spain', 'esp': 'Spain', 'spain': 'Spain',
  'pt': 'Portugal', 'prt': 'Portugal', 'portugal': 'Portugal',
  'nl': 'Netherlands', 'nld': 'Netherlands', 'netherlands': 'Netherlands', 'holland': 'Netherlands',
  'be': 'Belgium', 'bel': 'Belgium', 'belgium': 'Belgium',
  'ch': 'Switzerland', 'che': 'Switzerland', 'switzerland': 'Switzerland',
  'at': 'Austria', 'aut': 'Austria', 'austria': 'Austria',
  'se': 'Sweden', 'swe': 'Sweden', 'sweden': 'Sweden',
  'no': 'Norway', 'nor': 'Norway', 'norway': 'Norway',
  'dk': 'Denmark', 'dnk': 'Denmark', 'denmark': 'Denmark',
  'fi': 'Finland', 'fin': 'Finland', 'finland': 'Finland',
  'pl': 'Poland', 'pol': 'Poland', 'poland': 'Poland',
  'gr': 'Greece', 'grc': 'Greece', 'greece': 'Greece',
  'cz': 'Czechia', 'cze': 'Czechia', 'czech republic': 'Czechia', 'czechia': 'Czechia',
  'ru': 'Russia', 'rus': 'Russia', 'russia': 'Russia', 'russian federation': 'Russia',
  'ua': 'Ukraine', 'ukr': 'Ukraine', 'ukraine': 'Ukraine',
  'ro': 'Romania', 'rou': 'Romania', 'romania': 'Romania',
  'hu': 'Hungary', 'hun': 'Hungary', 'hungary': 'Hungary',

  // --- Asia & Pacific ---
  'in': 'India', 'ind': 'India', 'india': 'India',
  'cn': 'China', 'chn': 'China', 'china': 'China', 'prc': 'China',
  'jp': 'Japan', 'jpn': 'Japan', 'japan': 'Japan',
  'kr': 'South Korea', 'kor': 'South Korea', 'south korea': 'South Korea', 'republic of korea': 'South Korea',
  'kp': 'North Korea', 'prk': 'North Korea', 'north korea': 'North Korea',
  'au': 'Australia', 'aus': 'Australia', 'australia': 'Australia',
  'nz': 'New Zealand', 'nzl': 'New Zealand', 'new zealand': 'New Zealand',
  'sg': 'Singapore', 'sgp': 'Singapore', 'singapore': 'Singapore',
  'my': 'Malaysia', 'mys': 'Malaysia', 'malaysia': 'Malaysia',
  'ph': 'Philippines', 'phl': 'Philippines', 'philippines': 'Philippines',
  'id': 'Indonesia', 'idn': 'Indonesia', 'indonesia': 'Indonesia',
  'th': 'Thailand', 'tha': 'Thailand', 'thailand': 'Thailand',
  'vn': 'Vietnam', 'vnm': 'Vietnam', 'vietnam': 'Vietnam', 'viet nam': 'Vietnam',
  'pk': 'Pakistan', 'pak': 'Pakistan', 'pakistan': 'Pakistan',
  'bd': 'Bangladesh', 'bgd': 'Bangladesh', 'bangladesh': 'Bangladesh',
  'lk': 'Sri Lanka', 'lka': 'Sri Lanka', 'sri lanka': 'Sri Lanka',
  'np': 'Nepal', 'npl': 'Nepal', 'nepal': 'Nepal',
  'tw': 'Taiwan', 'twn': 'Taiwan', 'taiwan': 'Taiwan',
  'hk': 'Hong Kong', 'hkg': 'Hong Kong', 'hong kong': 'Hong Kong',

  // --- Middle East & Africa ---
  'ae': 'United Arab Emirates', 'uae': 'United Arab Emirates', 'are': 'United Arab Emirates', 'united arab emirates': 'United Arab Emirates',
  'sa': 'Saudi Arabia', 'sau': 'Saudi Arabia', 'saudi arabia': 'Saudi Arabia',
  'za': 'South Africa', 'zaf': 'South Africa', 'south africa': 'South Africa',
  'eg': 'Egypt', 'egy': 'Egypt', 'egypt': 'Egypt',
  'ng': 'Nigeria', 'nga': 'Nigeria', 'nigeria': 'Nigeria',
  'ke': 'Kenya', 'ken': 'Kenya', 'kenya': 'Kenya',
  'il': 'Israel', 'isr': 'Israel', 'israel': 'Israel',
  'tr': 'Turkey', 'tur': 'Turkey', 'turkey': 'Turkey', 'turkiye': 'Turkey',
  'ir': 'Iran', 'irn': 'Iran', 'iran': 'Iran',
  'iq': 'Iraq', 'irq': 'Iraq', 'iraq': 'Iraq',
  'kw': 'Kuwait', 'kwt': 'Kuwait', 'kuwait': 'Kuwait',
  'qa': 'Qatar', 'qat': 'Qatar', 'qatar': 'Qatar',
  'ma': 'Morocco', 'mar': 'Morocco', 'morocco': 'Morocco',
  'gh': 'Ghana', 'gha': 'Ghana', 'ghana': 'Ghana',
  'tz': 'Tanzania', 'tza': 'Tanzania', 'tanzania': 'Tanzania',
  'ug': 'Uganda', 'uga': 'Uganda', 'uganda': 'Uganda',

  // --- South America ---
  'br': 'Brazil', 'bra': 'Brazil', 'brazil': 'Brazil',
  'ar': 'Argentina', 'arg': 'Argentina', 'argentina': 'Argentina',
  'co': 'Colombia', 'col': 'Colombia', 'colombia': 'Colombia',
  'cl': 'Chile', 'chl': 'Chile', 'chile': 'Chile',
  'pe': 'Peru', 'per': 'Peru', 'peru': 'Peru',
  've': 'Venezuela', 'ven': 'Venezuela', 'venezuela': 'Venezuela',
  'ec': 'Ecuador', 'ecu': 'Ecuador', 'ecuador': 'Ecuador',
  'uy': 'Uruguay', 'ury': 'Uruguay', 'uruguay': 'Uruguay',
  'py': 'Paraguay', 'pry': 'Paraguay', 'paraguay': 'Paraguay',
  'bo': 'Bolivia', 'bol': 'Bolivia', 'bolivia': 'Bolivia'
};

const STATE_MAP = {
  // --- US States (50 States + DC + PR) ---
  'al': 'Alabama', 'alabama': 'Alabama',
  'ak': 'Alaska', 'alaska': 'Alaska',
  'az': 'Arizona', 'arizona': 'Arizona',
  'ar': 'Arkansas', 'arkansas': 'Arkansas',
  'ca': 'California', 'calif': 'California', 'california': 'California',
  'co': 'Colorado', 'colorado': 'Colorado',
  'ct': 'Connecticut', 'connecticut': 'Connecticut',
  'de': 'Delaware', 'delaware': 'Delaware',
  'fl': 'Florida', 'fla': 'Florida', 'florida': 'Florida',
  'ga': 'Georgia', 'georgia': 'Georgia',
  'hi': 'Hawaii', 'hawaii': 'Hawaii',
  'id': 'Idaho', 'idaho': 'Idaho',
  'il': 'Illinois', 'illinois': 'Illinois',
  'in': 'Indiana', 'indiana': 'Indiana',
  'ia': 'Iowa', 'iowa': 'Iowa',
  'ks': 'Kansas', 'kansas': 'Kansas',
  'ky': 'Kentucky', 'kentucky': 'Kentucky',
  'la': 'Louisiana', 'louisiana': 'Louisiana',
  'me': 'Maine', 'maine': 'Maine',
  'md': 'Maryland', 'maryland': 'Maryland',
  'ma': 'Massachusetts', 'mass': 'Massachusetts', 'massachusetts': 'Massachusetts',
  'mi': 'Michigan', 'michigan': 'Michigan',
  'mn': 'Minnesota', 'minnesota': 'Minnesota',
  'ms': 'Mississippi', 'mississippi': 'Mississippi',
  'mo': 'Missouri', 'missouri': 'Missouri',
  'mt': 'Montana', 'montana': 'Montana',
  'ne': 'Nebraska', 'nebraska': 'Nebraska',
  'nv': 'Nevada', 'nevada': 'Nevada',
  'nh': 'New Hampshire', 'new hampshire': 'New Hampshire',
  'nj': 'New Jersey', 'new jersey': 'New Jersey',
  'nm': 'New Mexico', 'new mexico': 'New Mexico',
  'ny': 'New York', 'new york': 'New York',
  'nc': 'North Carolina', 'north carolina': 'North Carolina',
  'nd': 'North Dakota', 'north dakota': 'North Dakota',
  'oh': 'Ohio', 'ohio': 'Ohio',
  'ok': 'Oklahoma', 'oklahoma': 'Oklahoma',
  'or': 'Oregon', 'oregon': 'Oregon',
  'pa': 'Pennsylvania', 'pennsylvania': 'Pennsylvania',
  'ri': 'Rhode Island', 'rhode island': 'Rhode Island',
  'sc': 'South Carolina', 'south carolina': 'South Carolina',
  'sd': 'South Dakota', 'south dakota': 'South Dakota',
  'tn': 'Tennessee', 'tennessee': 'Tennessee',
  'tx': 'Texas', 'tex': 'Texas', 'texas': 'Texas',
  'ut': 'Utah', 'utah': 'Utah',
  'vt': 'Vermont', 'vermont': 'Vermont',
  'va': 'Virginia', 'virginia': 'Virginia',
  'wa': 'Washington', 'washington': 'Washington',
  'wv': 'West Virginia', 'west virginia': 'West Virginia',
  'wi': 'Wisconsin', 'wisconsin': 'Wisconsin',
  'wy': 'Wyoming', 'wyoming': 'Wyoming',
  'dc': 'District of Columbia', 'washington dc': 'District of Columbia', 'district of columbia': 'District of Columbia',
  'pr': 'Puerto Rico', 'puerto rico': 'Puerto Rico',

  // --- Canadian Provinces ---
  'ab': 'Alberta', 'alberta': 'Alberta',
  'bc': 'British Columbia', 'british columbia': 'British Columbia',
  'mb': 'Manitoba', 'manitoba': 'Manitoba',
  'nb': 'New Brunswick', 'new brunswick': 'New Brunswick',
  'nl': 'Newfoundland and Labrador', 'newfoundland': 'Newfoundland and Labrador',
  'ns': 'Nova Scotia', 'nova scotia': 'Nova Scotia',
  'nt': 'Northwest Territories', 'northwest territories': 'Northwest Territories',
  'nu': 'Nunavut', 'nunavut': 'Nunavut',
  'on': 'Ontario', 'ontario': 'Ontario',
  'pe': 'Prince Edward Island', 'pei': 'Prince Edward Island',
  'qc': 'Quebec', 'quebec': 'Quebec',
  'sk': 'Saskatchewan', 'saskatchewan': 'Saskatchewan',
  'yt': 'Yukon', 'yukon': 'Yukon',

  // --- Australian States ---
  'act': 'Australian Capital Territory', 'australian capital territory': 'Australian Capital Territory',
  'nsw': 'New South Wales', 'new south wales': 'New South Wales',
  'qld': 'Queensland', 'queensland': 'Queensland',
  'sa': 'South Australia', 'south australia': 'South Australia',
  'tas': 'Tasmania', 'tasmania': 'Tasmania',
  'vic': 'Victoria', 'victoria': 'Victoria',
  'wa': 'Western Australia', 'western australia': 'Western Australia',

  // --- India States & Union Territories (Salesforce Defaults) ---
  'ap': 'Andhra Pradesh', 'andhra pradesh': 'Andhra Pradesh',
  'ar': 'Arunachal Pradesh', 'arunachal pradesh': 'Arunachal Pradesh', // Conflict with Arkansas (US) - Context matters!
  'as': 'Assam', 'assam': 'Assam',
  'br': 'Bihar', 'bihar': 'Bihar',
  'cg': 'Chhattisgarh', 'chhattisgarh': 'Chhattisgarh',
  'ga': 'Goa', 'goa': 'Goa', // Conflict with Georgia (US)
  'gj': 'Gujarat', 'gujarat': 'Gujarat',
  'hr': 'Haryana', 'haryana': 'Haryana',
  'hp': 'Himachal Pradesh', 'himachal pradesh': 'Himachal Pradesh',
  'jh': 'Jharkhand', 'jharkhand': 'Jharkhand',
  'ka': 'Karnataka', 'karnataka': 'Karnataka',
  'kl': 'Kerala', 'kerala': 'Kerala',
  'mp': 'Madhya Pradesh', 'madhya pradesh': 'Madhya Pradesh',
  'mh': 'Maharashtra', 'maharashtra': 'Maharashtra',
  'mn': 'Manipur', 'manipur': 'Manipur',
  'ml': 'Meghalaya', 'meghalaya': 'Meghalaya',
  'mz': 'Mizoram', 'mizoram': 'Mizoram',
  'nl': 'Nagaland', 'nagaland': 'Nagaland', // Conflict with Newfoundland (Canada)
  'od': 'Odisha', 'odisha': 'Odisha',
  'pb': 'Punjab', 'punjab': 'Punjab',
  'rj': 'Rajasthan', 'rajasthan': 'Rajasthan',
  'sk': 'Sikkim', 'sikkim': 'Sikkim', // Conflict with Saskatchewan (Canada)
  'tn': 'Tamil Nadu', 'tamil nadu': 'Tamil Nadu', // Conflict with Tennessee (US)
  'ts': 'Telangana', 'telangana': 'Telangana',
  'tr': 'Tripura', 'tripura': 'Tripura',
  'up': 'Uttar Pradesh', 'uttar pradesh': 'Uttar Pradesh',
  'uk': 'Uttarakhand', 'uttarakhand': 'Uttarakhand',
  'wb': 'West Bengal', 'west bengal': 'West Bengal',
  'an': 'Andaman and Nicobar Islands', 'andaman and nicobar islands': 'Andaman and Nicobar Islands',
  'ch': 'Chandigarh', 'chandigarh': 'Chandigarh',
  'dn': 'Dadra and Nagar Haveli', 'dadra and nagar haveli': 'Dadra and Nagar Haveli',
  'dd': 'Daman and Diu', 'daman and diu': 'Daman and Diu',
  'dl': 'Delhi', 'delhi': 'Delhi',
  'jk': 'Jammu and Kashmir', 'jammu and kashmir': 'Jammu and Kashmir',
  'la': 'Ladakh', 'ladakh': 'Ladakh',
  'ld': 'Lakshadweep', 'lakshadweep': 'Lakshadweep',
  'py': 'Puducherry', 'puducherry': 'Puducherry',

  // --- Brazil States (Salesforce Defaults) ---
  'ac': 'Acre', 'acre': 'Acre',
  'al': 'Alagoas', 'alagoas': 'Alagoas', // Conflict with Alabama (US)
  'ap': 'Amapá', 'amapá': 'Amapá', 'amapa': 'Amapá',
  'am': 'Amazonas', 'amazonas': 'Amazonas',
  'ba': 'Bahia', 'bahia': 'Bahia',
  'ce': 'Ceará', 'ceará': 'Ceará', 'ceara': 'Ceará',
  'df': 'Distrito Federal', 'distrito federal': 'Distrito Federal',
  'es': 'Espírito Santo', 'espírito santo': 'Espírito Santo', 'espirito santo': 'Espírito Santo',
  'go': 'Goiás', 'goiás': 'Goiás', 'goias': 'Goiás',
  'ma': 'Maranhão', 'maranhão': 'Maranhão', 'maranhao': 'Maranhão',
  'mt': 'Mato Grosso', 'mato grosso': 'Mato Grosso',
  'ms': 'Mato Grosso do Sul', 'mato grosso do sul': 'Mato Grosso do Sul', // Conflict with Mississippi (US)
  'mg': 'Minas Gerais', 'minas gerais': 'Minas Gerais',
  'pa': 'Pará', 'pará': 'Pará', 'para': 'Pará', // Conflict with Pennsylvania (US)
  'pb': 'Paraíba', 'paraíba': 'Paraíba', 'paraiba': 'Paraíba',
  'pr': 'Paraná', 'paraná': 'Paraná', 'parana': 'Paraná', // Conflict with Puerto Rico (US)
  'pe': 'Pernambuco', 'pernambuco': 'Pernambuco',
  'pi': 'Piauí', 'piauí': 'Piauí', 'piaui': 'Piauí',
  'rj': 'Rio de Janeiro', 'rio de janeiro': 'Rio de Janeiro',
  'rn': 'Rio Grande do Norte', 'rio grande do norte': 'Rio Grande do Norte',
  'rs': 'Rio Grande do Sul', 'rio grande do sul': 'Rio Grande do Sul',
  'ro': 'Rondônia', 'rondônia': 'Rondônia', 'rondonia': 'Rondônia',
  'rr': 'Roraima', 'roraima': 'Roraima',
  'sc': 'Santa Catarina', 'santa catarina': 'Santa Catarina', // Conflict with South Carolina (US)
  'sp': 'São Paulo', 'são paulo': 'São Paulo', 'sao paulo': 'São Paulo',
  'se': 'Sergipe', 'sergipe': 'Sergipe',
  'to': 'Tocantins', 'tocantins': 'Tocantins',

  // --- Mexico States (Salesforce Defaults) ---
  'aguascalientes': 'Aguascalientes', 'ags': 'Aguascalientes',
  'baja california': 'Baja California', 'bc': 'Baja California',
  'baja california sur': 'Baja California Sur', 'bcs': 'Baja California Sur',
  'campeche': 'Campeche', 'camp': 'Campeche',
  'chiapas': 'Chiapas', 'chis': 'Chiapas',
  'chihuahua': 'Chihuahua', 'chih': 'Chihuahua',
  'ciudad de mexico': 'Ciudad de México', 'ciudad de méxico': 'Ciudad de México', 'cdmx': 'Ciudad de México',
  'coahuila': 'Coahuila', 'coah': 'Coahuila',
  'colima': 'Colima', 'col': 'Colima',
  'durango': 'Durango', 'dgo': 'Durango',
  'guanajuato': 'Guanajuato', 'gto': 'Guanajuato',
  'guerrero': 'Guerrero', 'gro': 'Guerrero',
  'hidalgo': 'Hidalgo', 'hgo': 'Hidalgo',
  'jalisco': 'Jalisco', 'jal': 'Jalisco',
  'mexico state': 'México', 'méxico': 'México', 'estado de mexico': 'México', 'mex': 'México',
  'michoacan': 'Michoacán', 'michoacán': 'Michoacán', 'mich': 'Michoacán',
  'morelos': 'Morelos', 'mor': 'Morelos',
  'nayarit': 'Nayarit', 'nay': 'Nayarit',
  'nuevo leon': 'Nuevo León', 'nuevo león': 'Nuevo León', 'nl': 'Nuevo León',
  'oaxaca': 'Oaxaca', 'oax': 'Oaxaca',
  'puebla': 'Puebla', 'pue': 'Puebla',
  'queretaro': 'Querétaro', 'querétaro': 'Querétaro', 'qro': 'Querétaro',
  'quintana roo': 'Quintana Roo', 'q roo': 'Quintana Roo', 'qroo': 'Quintana Roo',
  'san luis potosi': 'San Luis Potosí', 'san luis potosí': 'San Luis Potosí', 'slp': 'San Luis Potosí',
  'sinaloa': 'Sinaloa', 'sin': 'Sinaloa',
  'sonora': 'Sonora', 'son': 'Sonora',
  'tabasco': 'Tabasco', 'tab': 'Tabasco',
  'tamaulipas': 'Tamaulipas', 'tamps': 'Tamaulipas',
  'tlaxcala': 'Tlaxcala', 'tlax': 'Tlaxcala',
  'veracruz': 'Veracruz', 'ver': 'Veracruz',
  'yucatan': 'Yucatán', 'yucatán': 'Yucatán', 'yuc': 'Yucatán',
  'zacatecas': 'Zacatecas', 'zac': 'Zacatecas',

  // --- Italy Provinces (Salesforce Defaults - Partial selection of major ones) ---
  'roma': 'Roma', 'rm': 'Roma', 'rome': 'Roma',
  'milano': 'Milano', 'mi': 'Milano', 'milan': 'Milano',
  'napoli': 'Napoli', 'na': 'Napoli', 'naples': 'Napoli',
  'torino': 'Torino', 'to': 'Torino', 'turin': 'Torino',
  'palermo': 'Palermo', 'pa': 'Palermo',
  'genova': 'Genova', 'ge': 'Genova', 'genoa': 'Genova',
  'bologna': 'Bologna', 'bo': 'Bologna',
  'firenze': 'Firenze', 'fi': 'Firenze', 'florence': 'Firenze',
  'venezia': 'Venezia', 've': 'Venezia', 'venice': 'Venezia',

  // --- Ireland Counties (Salesforce Defaults) ---
  'carlow': 'Carlow',
  'cavan': 'Cavan',
  'clare': 'Clare',
  'cork': 'Cork',
  'donegal': 'Donegal',
  'dublin': 'Dublin',
  'galway': 'Galway',
  'kerry': 'Kerry',
  'kildare': 'Kildare',
  'kilkenny': 'Kilkenny',
  'laois': 'Laois',
  'leitrim': 'Leitrim',
  'limerick': 'Limerick',
  'longford': 'Longford',
  'louth': 'Louth',
  'mayo': 'Mayo',
  'meath': 'Meath',
  'monaghan': 'Monaghan',
  'offaly': 'Offaly',
  'roscommon': 'Roscommon',
  'sligo': 'Sligo',
  'tipperary': 'Tipperary',
  'waterford': 'Waterford',
  'westmeath': 'Westmeath',
  'wexford': 'Wexford',
  'wicklow': 'Wicklow'
};

const RECORD_TYPE_MAP = {
  'Account': {
    'B2B Customer': '012gL000001quLhQAI',
    'Partner': '012gL000001quLhQAI',
    'Vendor': '012gL000001quLiQAI'
  },
  'Contact': {
    'Standard': '012gL000001quLhQAI',
    'Executive': '012gL000001quLiQAI'
  },
  'Opportunity': {
    'New Business': '012gL000001quLhQAI',
    'Renewal': '012gL000001quLiQAI'
  }
};

module.exports = {
  COUNTRY_MAP,
  STATE_MAP,
  RECORD_TYPE_MAP
};